name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EPICURE_SSH_KEY }}
      
      - name: Deploy via PM2 on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.20.51.121 'cd ~/epicure-backend && pm2 deploy ecosystem.json production'
