name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EPICURE_SSH_KEY }}
          
      - name: Install PM2
        run: npm install -g pm2

      - name: Deploy with PM2
        run: pm2 deploy ecosystem.json production
